httpPort: 13000
metricPort: 15858
appName: hall
log:
  level: DEBUG
  fileName: "./logs"
  maxSize: 500
  maxAge: 28
  maxBackups: 3
db:
  mongo:
    url: mongodb://127.0.0.1:27017
    userName: root
    password: root
    minPoolSize: 10
    maxPoolSize: 100
    db: qpgame
  redis:
    addr: 127.0.0.1:6379
    poolSize: 10
    minIdleConns: 1
    password:
jwt:
  secret: 123456
  exp: 7
