metricPort: 15853
appName: user
log:
  level: DEBUG
  fileName: "./logs"
  maxSize: 500
  maxAge: 28
  maxBackups: 3
grpc:
  addr: 127.0.0.1:11400
etcd:
  addrs:
    - 127.0.0.1:2379
  register:
    name: user
    addr: 127.0.0.1:11400
    version: v1
    weight: 10
    ttl: 10
db:
  mongo:
    url: mongodb://127.0.0.1:27017
    userName: root
    password: root
    minPoolSize: 10
    maxPoolSize: 100
    db: qpgame
  redis:
    addr: 127.0.0.1:6379
    poolSize: 10
    minIdleConns: 1
    password:
jwt:
  secret: 123456
  exp: 7